# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B7P6vciWbxgz_0cq1TFDrOfixB6-KzOg
"""

import warnings
warnings.filterwarnings("ignore")

import io
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import seaborn as sns
import streamlit as st

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import (
    KMeans, AgglomerativeClustering, DBSCAN, MeanShift, estimate_bandwidth
)
from sklearn.mixture import GaussianMixture
from sklearn.metrics import (
    silhouette_score, davies_bouldin_score, calinski_harabasz_score
)
from scipy.cluster.hierarchy import dendrogram, linkage

# ─────────────────────────────────────────────
# PAGE CONFIG
# ─────────────────────────────────────────────
st.set_page_config(
    page_title="Global Development Clustering",
    page_icon="🌍",
    layout="wide"

# ─────────────────────────────────────────────
# CONSTANTS
# ─────────────────────────────────────────────
FEATURE_COLS = [
    "GDP", "Health Exp/Capita", "Internet Usage",
    "Birth Rate", "Life Expectancy Female", "Life Expectancy Male",
    "Avg Life Expectancy", "CO2 Emissions", "Business Tax Rate",
    "Tourism Inbound", "Tourism Outbound",
]

COLS_TO_CLEAN = [
    "GDP", "Tourism Inbound", "Tourism Outbound",
    "Health Exp/Capita", "Business Tax Rate"
]

# ─────────────────────────────────────────────
# LOAD + PREPROCESS
# ─────────────────────────────────────────────
@st.cache_data
def load_and_preprocess(file_bytes):
    # ✅ FIX: use BytesIO
    df = pd.read_excel(io.BytesIO(file_bytes))

    # Clean symbols
    for col in COLS_TO_CLEAN:
        if col in df.columns:
            df[col] = df[col].replace(r"[\$,%]", "", regex=True)
            df[col] = pd.to_numeric(df[col], errors="coerce")

    # Drop column if exists
    df.drop(columns=["Ease of Business"], inplace=True, errors="ignore")

    # Fill missing
    df.fillna(df.median(numeric_only=True), inplace=True)

    # Outlier capping
    for col in df.select_dtypes(include=["int64", "float64"]).columns:
        Q1, Q3 = df[col].quantile(0.25), df[col].quantile(0.75)
        IQR = Q3 - Q1
        df[col] = np.clip(df[col], Q1 - 1.5 * IQR, Q3 + 1.5 * IQR)

    # Feature engineering
    if "Life Expectancy Female" in df.columns and "Life Expectancy Male" in df.columns:
        df["Avg Life Expectancy"] = (
            df["Life Expectancy Female"] + df["Life Expectancy Male"]
        ) / 2

    return df

# ─────────────────────────────────────────────
# FEATURE ENGINEERING
# ─────────────────────────────────────────────
def get_features(df):
    cols = [c for c in FEATURE_COLS if c in df.columns]
    X = df[cols]
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    return X_scaled, cols


def get_pca(X_scaled):
    pca = PCA(n_components=2, random_state=42)
    X_pca = pca.fit_transform(X_scaled)
    return X_pca, pca.explained_variance_ratio_

# ─────────────────────────────────────────────
# METRICS
# ─────────────────────────────────────────────
def eval_metrics(X, labels):
    if len(set(labels)) < 2:
        return {"Silhouette": None, "DB": None, "CH": None}

    return {
        "Silhouette": silhouette_score(X, labels),
        "DB": davies_bouldin_score(X, labels),
        "CH": calinski_harabasz_score(X, labels)
    }

# ─────────────────────────────────────────────
# ELBOW FIX
# ─────────────────────────────────────────────
@st.cache_data
def compute_elbow(X_bytes, n_features):
    X = np.frombuffer(X_bytes, dtype=np.float64).reshape(-1, n_features)

    k_range = range(2, 11)
    inertia = []
    silh = []

    for k in k_range:
        km = KMeans(n_clusters=k, random_state=42, n_init=10)
        labels = km.fit_predict(X)

        inertia.append(km.inertia_)
        silh.append(silhouette_score(X, labels))

    return list(k_range), inertia, silh

# ─────────────────────────────────────────────
# SIDEBAR
# ─────────────────────────────────────────────
st.sidebar.title("🌍 Clustering App")

uploaded = st.sidebar.file_uploader("Upload Excel", type=["xlsx"])
k_manual = st.sidebar.slider("Clusters (0 = auto)", 0, 10, 0)

# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────
if uploaded is None:
    st.info("Upload dataset to continue")
    st.stop()


# ✅ FIX: use getvalue()
df = load_and_preprocess(uploaded.getvalue())

X_scaled, feat_cols = get_features(df)
X_pca, evr = get_pca(X_scaled)

# ✅ FIX: pass shape
k_range, inertia, silh = compute_elbow(
    X_scaled.tobytes(), X_scaled.shape[1]
)

auto_k = k_range[silh.index(max(silh))]
best_k = k_manual if k_manual >= 2 else auto_k

# ─────────────────────────────────────────────
# OUTPUT
# ─────────────────────────────────────────────
st.title("🌍 Global Development Clustering")

st.metric("Auto K", auto_k)

# Plot elbow
fig, ax = plt.subplots()
ax.plot(k_range, inertia)
ax.set_title("Elbow")
st.pyplot(fig)

# KMeans
km = KMeans(n_clusters=best_k, random_state=42, n_init=10)
labels = km.fit_predict(X_scaled)

df["Cluster"] = labels

# PCA plot
fig2, ax2 = plt.subplots()
scatter = ax2.scatter(X_pca[:, 0], X_pca[:, 1], c=labels)
ax2.set_title("Clusters (PCA)")
st.pyplot(fig2)

# Data preview
st.dataframe(df.head())



